// resources/js/pages/Dashboard.vue
<script setup lang="ts">
import MobileNav from '@/components/MobileNav.vue';
import SidebarNav from '@/components/SidebarNav.vue';

const props = defineProps(['user', 'recentMatches']);

const balance = props.user.balance;
const tokens = props.user.token_balance;
const recentMatches = props.recentMatches;
</script>

<template>
    <div class="flex min-h-screen bg-gray-50">
        <!-- Sidebar -->
        <SidebarNav />

        <!-- Main content -->
        <main class="flex-1 space-y-6 p-4 pb-6">
            <h1 class="text-2xl font-bold">Your Dashboard</h1>
            <p>Welcome, {{ user.name }}</p>

            <!-- Wallet + Tokens -->
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div class="rounded-lg bg-white p-4 shadow">
                    <p class="text-sm text-gray-500">Wallet Balance</p>
                    <p class="text-xl font-semibold">KES {{ Number(balance).toLocaleString() }}</p>
                </div>
                <div class="rounded-lg bg-white p-4 shadow">
                    <p class="text-sm text-gray-500">Game Tokens</p>
                    <p class="text-xl font-semibold text-pink-600">🎟️ {{ tokens }}</p>
                </div>
            </div>

            <!-- Recent Matches -->
            <div class="mb-[50px]">
                <h2 class="mb-3 text-lg font-medium">Recent Matches</h2>

                <div v-if="recentMatches.length" class="space-y-2">
                    <div v-for="(match, i) in recentMatches" :key="i" class="flex items-center justify-between rounded-lg bg-white p-4 shadow-sm">
                        <div>
                            <p class="font-semibold">vs. {{ match.opponent }}</p>
                            <p class="text-sm text-gray-500">
                                {{ match.platform }} · 🎟️ {{ match.tokens }} · KES {{ match.stake }} · {{ match.date }}
                            </p>
                        </div>
                        <span
                            class="rounded-full px-2 py-1 text-sm font-medium"
                            :class="{
                                'bg-green-100 text-green-600': match.result === 'Win',
                                'bg-red-100 text-red-600': match.result === 'Loss',
                                'bg-yellow-100 text-yellow-700': match.result === 'Draw',
                                'bg-gray-200 text-gray-600': match.result === 'Anomaly',
                            }"
                        >
                            {{ match.result }}
                        </span>
                    </div>
                </div>

                <div v-else class="text-sm text-gray-500">You have not played any matches yet.</div>
            </div>
        </main>

        <!-- Mobile Nav -->
        <MobileNav />
    </div>
</template>

// chess-gaming-platform/src/app/(dashboard)/dashboard/page.tsx
"use client"

import { useSession } from "next-auth/react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { formatCurrency } from "@/lib/utils"
import { Wallet, Trophy, Gamepad2, TrendingUp } from "lucide-react"

export default function DashboardPage() {
  const { data: session } = useSession()

  // Mock data - in real app, fetch from API
  const stats = {
    balance: 5000,
    tokens: 25,
    wins: 12,
    totalMatches: 18,
  }

  const recentMatches = [
    {
      id: 1,
      opponent: "ChessMaster",
      result: "Win",
      stake: 500,
      tokens: 5,
      date: "2024-01-15",
    },
    {
      id: 2,
      opponent: "PawnPusher",
      result: "Loss",
      stake: 300,
      tokens: 3,
      date: "2024-01-14",
    },
    {
      id: 3,
      opponent: "KnightRider",
      result: "Draw",
      stake: 200,
      tokens: 2,
      date: "2024-01-13",
    },
  ]

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground">
          Welcome back, {session?.user?.name}!
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Wallet Balance</CardTitle>
            <Wallet className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{formatCurrency(stats.balance)}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Game Tokens</CardTitle>
            <Trophy className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-pink-600">🎟️ {stats.tokens}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Wins</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">{stats.wins}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Matches</CardTitle>
            <Gamepad2 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats.totalMatches}</div>
          </CardContent>
        </Card>
      </div>

      {/* Recent Matches */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Matches</CardTitle>
          <CardDescription>Your latest game results</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {recentMatches.map((match) => (
              <div
                key={match.id}
                className="flex items-center justify-between rounded-lg border p-4"
              >
                <div>
                  <p className="font-semibold">vs. {match.opponent}</p>
                  <p className="text-sm text-muted-foreground">
                    🎟️ {match.tokens} tokens • {formatCurrency(match.stake)} • {match.date}
                  </p>
                </div>
                <span
                  className={`rounded-full px-3 py-1 text-sm font-medium ${
                    match.result === "Win"
                      ? "bg-green-100 text-green-700"
                      : match.result === "Loss"
                      ? "bg-red-100 text-red-700"
                      : "bg-yellow-100 text-yellow-700"
                  }`}
                >
                  {match.result}
                </span>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
