// resources/js/components/MobileNav.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';
import { CreditCard, Home, Joystick, Settings } from 'lucide-vue-next';

const isActive = (routeName: string) => {
    const currentRoute = route().current();
    return currentRoute === routeName || currentRoute.startsWith(routeName + '.');
};

</script>

<template>
    <nav class="fixed right-0 bottom-0 left-0 z-50 flex justify-around border-t bg-white py-3 shadow md:hidden">

        <Link :href="route('dashboard')" class="flex flex-col items-center text-gray-600 hover:text-blue-600">
            <Home class="h-6 w-6" :class="{ 'text-blue-600': isActive('dashboard') }" />
        </Link>

        <Link :href="route('matches.active')" class="flex flex-col items-center text-gray-600 hover:text-blue-600">
            <Joystick class="h-6 w-6" :class="{ 'text-blue-600': isActive('matches') }" />
        </Link>

        <Link :href="route('wallet.main')" class="flex flex-col items-center text-gray-600 hover:text-blue-600">
            <CreditCard class="h-6 w-6" :class="{ 'text-blue-600': isActive('wallet') }" />
        </Link>

        <Link :href="route('profile.edit')" class="flex flex-col items-center text-gray-600 hover:text-blue-600">
            <Settings class="h-6 w-6" :class="{ 'text-blue-600': isActive('profile.edit') || isActive('password.edit') }" />
        </Link>

    </nav>
</template>

// chess-gaming-platform/src/components/layout/mobile-nav.tsx
"use client"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Home, Gamepad2, Wallet, Settings } from "lucide-react"
import Link from "next/link"
import { usePathname } from "next/navigation"

const navigation = [
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: Home,
  },
  {
    name: "Matches",
    href: "/matches",
    icon: Gamepad2,
  },
  {
    name: "Wallet",
    href: "/wallet",
    icon: Wallet,
  },
  {
    name: "Settings",
    href: "/settings",
    icon: Settings,
  },
]

export function MobileNav() {
  const pathname = usePathname()

  return (
    <div className="fixed bottom-0 left-0 right-0 z-50 bg-background border-t md:hidden">
      <div className="grid grid-cols-4 gap-1 p-2">
        {navigation.map((item) => (
          <Button
            key={item.name}
            variant={pathname === item.href ? "secondary" : "ghost"}
            size="sm"
            className="flex flex-col h-auto py-2"
            asChild
          >
            <Link href={item.href}>
              <item.icon className="h-4 w-4 mb-1" />
              <span className="text-xs">{item.name}</span>
            </Link>
          </Button>
        ))}
      </div>
    </div>
  )
}
